name: KernelSU With SUSFS

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: "Kernel branch (e.g., sm8475)"
        required: true
        default: 'sm8475'
      FEIL:
        description: "Config file (e.g., oneplus_ace2_v)"
        required: true
        default: 'oneplus_ace2_v'
      CPUD:
        description: "Processor codename (e.g., waipio)"
        required: true
        default: 'waipio'
      ANDROID_VERSION:
        description: "Android version for kernel (e.g., android12)"
        required: true
        default: 'android12'
      KERNEL_VERSION:
        description: "Kernel version (e.g., 5.10)"
        required: true
        default: '5.10'
      BUILD_METHOD:
        description: "Build method (e.g., gki)"
        required: true
        default: 'gki'
      KernelSU:
        description: "Enable KernelSU integration"
        required: true
        type: boolean
        default: true
      SUSFS_ENABLED:
        description: "Enable SUSFS integration"
        required: true
        type: boolean
        default: true
      SUSFS_VERSION:
        description: "SUSFS version (e.g., v1.5.5)"
        required: true
        default: 'v1.5.5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git
        run: |
          git config --global user.name "build"
          git config --global user.email "70756062@qq.com"

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3 git curl patch bc bison flex libssl-dev clang lld
          export CC="clang"
          export CLANG_TRIPLE="aarch64-linux-gnu-"
          export LDFLAGS="-fuse-ld=lld"
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CLANG_TRIPLE=$CLANG_TRIPLE" >> $GITHUB_ENV
          echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV

      - name: Install repo tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
          repo sync
          rm kernel_platform/common/android/abi_gki_protected_exports_* 2>/dev/null || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* 2>/dev/null || echo "No protected exports!"
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion

      - name: Set LTO to THIN
        run: |
          cd kernel_workspace/kernel_platform
          sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "./common/arch/arm64/configs/gki_defconfig"
          sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "./common/arch/arm64/configs/gki_defconfig"
          sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "./common/arch/arm64/configs/gki_defconfig"

      - name: Set up KernelSU (5ec1cff Fork)
        if: github.event.inputs.KernelSU == 'true'
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/refs/heads/main/kernel/setup.sh" | bash -
          cd KernelSU
          KSU_VERSION=$(git rev-list --count HEAD)
          echo "KSUVER=$((KSU_VERSION + 10200))" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=16*/DKSU_VERSION=${{ env.KSUVER }}/" kernel/Makefile

      - name: Set up SUSFS and Apply Patches
        if: github.event.inputs.SUSFS_ENABLED == 'true'
        run: |
          cd kernel_workspace
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
          git clone https://github.com/WildPlusKernel/kernel_patches.git
          git clone https://github.com/TanakaLun/kernel_patches4mksu.git
          cd kernel_platform
          cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
          cp -r ../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp -r ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          cd common
          patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || echo "Patch applied with conflicts, continuing..."
          cd ../KernelSU
          cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
          patch -p1 --forward < 10_enable_susfs_for_ksu.patch || echo "Patch applied with conflicts, continuing..."
          cp ../../kernel_patches/mksu/mksu_susfs.patch ./
          patch -p1 < mksu_susfs.patch || echo "Patch conflicts detected, continuing with unresolved changes..."
          cp ../../kernel_patches/hooks/new_hooks.patch ./
          patch -p1 -F 3 < new_hooks.patch || echo "Patch applied with conflicts, continuing..."
          cp ../../kernel_patches/mksu/fix.patch ./
          patch -p1 < fix.patch || echo "Patch conflicts detected, continuing with unresolved changes..."
          cp ../../kernel_patches4mksu/mksu/vfs_fix.patch ./
          patch -p1 < vfs_fix.patch
          cd ../

          # Add KSU configuration settings
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_WITH_KPROBES=n" >> ./common/arch/arm64/configs/gki_defconfig

          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig          
          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
                              
      - name: Build kernel
        run: |
          cd kernel_workspace
          export CC="clang"
          export CLANG_TRIPLE="aarch64-linux-gnu-"
          export LDFLAGS="-fuse-ld=lld"
          ./kernel_platform/oplus/build/oplus_build_kernel.sh ${{ github.event.inputs.CPUD }} ${{ github.event.inputs.BUILD_METHOD }}

      - name: Make AnyKernel3
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cp kernel_workspace/kernel_platform/out/msm-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.CPUD }}-gki/dist/Image ./AnyKernel3/
          cd AnyKernel3
          zip -r9 AnyKernel3_KernelSU_SUSFS_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}.zip *

      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_KernelSU_SUSFS_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
          path: ./AnyKernel3/AnyKernel3_KernelSU_SUSFS_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}.zip

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Image_KernelSU_SUSFS_${{ env.KSUVER }}_${{ github.event.inputs.FEIL }}
          path: kernel_workspace/kernel_platform/out/msm-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.CPUD }}-gki/dist/Image
